name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make build
      run:  make build

    - name: make test
      run: make test
      env:
        TF_CLI_CONFIG_FILE: dev.tfrc
        TF_VAR_ZEDCLOUD_TOKEN: ${{ secrets.TF_VAR_ZEDCLOUD_TOKEN }}
        TF_VAR_ZEDCLOUD_URL : ${{ vars.TF_VAR_zedcloud_url }}
